Repository andrechristikan/ack-nestjs-boilerplate-mongoose, pull requests merged in 2022-06, with the labels that each got.

#169 Fixed typo in permission table.
  src/permission/permission.constant.ts
Labels: minor

#174 Filled missing setting locale.
  src/message/languages/en/setting.json
Labels: feature, minor

#178 fix user schema hook mongoose
  src/user/schema/user.schema.ts
Labels: bug, minor
